(require "./re.scm")

(let* ((s "(1+0)*1")
	   (nfa (fa-renum (string->NFA s)))
	   (dfa (fa-renum (NFA->DFA nfa))))
  ;(fa-draw dfa s "101dfa.gif")
  (map print (NFA->Table nfa))
  (let1 tab (DFA->Table dfa)
	(map print tab)
	(let1 scanner (Table->Scanner tab)
	  (print "10101: " (scanner "10101"))
	  (print "10100: " (scanner "10100"))
	  (print "1: " (scanner "1"))
	  (print "(empty string): " (scanner ""))
	  )))
