(require "./re.scm")

(let* ((s "(1+0)*1")
	   (nfa (fa-renum (string->NFA s)))
	   (dfa (fa-renum (NFA->DFA nfa))))
  ;(fa-draw dfa s "101dfa.gif")
  (map print (NFA->Table nfa))
  (map print (DFA->Table dfa))
(print "---")

(let1 scanner (DFA->Scanner1 dfa)
(print "---")
	(print "10101: " (scanner "10101"))
	(print "10100: " (scanner "10100"))
	(print "1: " (scanner "1"))
	(print "(empty string): " (scanner ""))
	)

  (let1 scanner (DFA->Scanner dfa 50)
	(print (DFA->Array dfa 50))
	(print "10101: " (scanner "10101"))
	(print "10100: " (scanner "10100"))
	(print "1: " (scanner "1"))
	(print "(empty string): " (scanner ""))
	))
